# Generated by Django 2.1.2 on 2018-10-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(null=True, upload_to='')),
                ('website', models.URLField(null=True)),
                ('bio', models.TextField(null=True)),
                ('phone', models.CharField(max_length=140, null=True)),
                ('gender', models.CharField(choices=[('N', 'Not specified'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=1)),
                ('followers', models.ManyToManyField(blank=True, to='accounts.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='profiles', to='accounts.Profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
