# Generated by Django 2.1.2 on 2018-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181004_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
