# Generated by Django 2.1.2 on 2018-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_verification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('N', 'Not specified'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1),
        ),
    ]
